# Generated by Django 4.2.4 on 2023-10-17 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0002_init_training_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr_mn_wk', models.CharField(db_comment='년-월-주차', max_length=10)),
                ('year', models.IntegerField(db_comment='년')),
                ('month', models.IntegerField(db_comment='월')),
                ('week', models.IntegerField(db_comment='주차')),
                ('start_date', models.DateField(db_comment='시작일 (월)')),
                ('end_date', models.DateField(db_comment='종료일 (일)')),
                ('friday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='friday', to='session.session')),
                ('monday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='monday', to='session.session')),
                ('saturday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saturday', to='session.session')),
                ('sunday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sunday', to='session.session')),
                ('thursday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thursday', to='session.session')),
                ('tuesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tuesday', to='session.session')),
                ('wednesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wednesday', to='session.session')),
            ],
            options={
                'verbose_name': 'week',
                'verbose_name_plural': 'weeks',
                'db_table': 'week',
                'db_table_comment': '훈련',
                'indexes': [models.Index(fields=['yr_mn_wk'], name='weekly_index')],
            },
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('yr_mn_wk',), name='weekly_unique'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.CheckConstraint(check=models.Q(('year__gte', 2000)), name='year_gte_2000'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.CheckConstraint(check=models.Q(('year__lte', 9999)), name='year_lte_9999'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.CheckConstraint(check=models.Q(('month__gte', 1)), name='month_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.CheckConstraint(check=models.Q(('month__lte', 12)), name='month_lte_12'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.CheckConstraint(check=models.Q(('week__gte', 1)), name='week_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.CheckConstraint(check=models.Q(('week__lte', 5)), name='week_lte_5'),
        ),
    ]
