# Generated by Django 4.2.4 on 2023-11-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0002_remove_week_weekly_unique_alter_week_yr_mn_wk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='yr_mn_wk',
            field=models.CharField(db_comment='년 월 주차', max_length=20, unique=True),
        ),
    ]
