# Generated by Django 4.2.4 on 2023-10-08 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'training_type',
                'verbose_name_plural': 'training_types',
                'db_table': 'training_type',
                'db_table_comment': '훈련 유형',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_comment='훈련 날짜')),
                ('day', models.IntegerField(choices=[(1, '월요일'), (2, '화요일'), (3, '수요일'), (4, '목요일'), (5, '금요일'), (6, '토요일'), (7, '일요일')], db_comment='훈련 요일')),
                ('start_time', models.TimeField(db_comment='훈련 시작 시간')),
                ('end_time', models.TimeField(db_comment='훈련 종료 시간')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='session.trainingtype')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'db_table': 'session',
                'db_table_comment': '세션 = 훈련 한 타임',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coming', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
                'db_table': 'attendance',
                'db_table_comment': '출석',
                'unique_together': {('user', 'session')},
            },
        ),
    ]
