# Generated by Django 4.2.4 on 2023-10-08 14:19

from django.db import migrations

from participation.session.models import TrainingType

def bulk_insert_training_types(apps, schema_editor):
    TrainingType.objects.bulk_create([
        TrainingType(type="일반", description="일반 훈련"),
        TrainingType(type="일반-필참-오후", description="필수 참여 오후 훈련 (주로 화요일)"),
        TrainingType(type="일반-필참-오전", description="필수 참여 오전 훈련 (주로 토요일)"),
        TrainingType(type="시합", description="시합"),
        TrainingType(type="청백전", description="청백전"),
        TrainingType(type="훈련없음", description="훈련 없음"),
    ])

def bulk_insert_training_types_reverse(apps, schema_editor):
    TrainingType.objects.filter(type__in=[
        "일반",
        "일반-필참-오후",
        "일반-필참-오전",
        "시합",
        "청백전",
        "훈련없음",
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            bulk_insert_training_types,         ## migrate 수행 시 데이터 생성
            bulk_insert_training_types_reverse  ## migrate rollback 시 데이터 삭제
        ),
    ]
