# Generated by Django 4.2.4 on 2023-10-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_init_training_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(db_comment='훈련 종료 예상 시각'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(db_comment='집합 시각 (훈련 시작 시각)'),
        ),
    ]
