# Generated by Django 4.2.4 on 2023-11-02 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_alter_session_end_time_alter_session_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(db_comment='훈련 종료 예상 시각', default=datetime.time(23, 59, 59)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(db_comment='집합 시각 (훈련 시작 시각)', default=datetime.time(0, 0)),
        ),
    ]
