# Generated by Django 4.2.4 on 2023-10-24 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_phone_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(db_comment="전화번호는 '010-xxxx-xxxx' 형식으로만 받음", error_messages={'invalid': "전화번호는 '010-xxxx-xxxx' 형식으로만 받습니다", 'unique': '이미 존재하는 전화번호입니다'}, max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^010-\\d{4}-\\d{4}$')]),
        ),
    ]
