# Generated by Django 4.2.4 on 2023-10-03 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.IntegerField(choices=[(1, '관리자'), (2, '주장'), (3, '부주장'), (4, '매니저'), (5, '부원'), (6, '군입대자'), (7, '비활동부원')], default=5)),
                ('name', models.CharField(db_comment='이름', max_length=32)),
                ('phone_number', models.CharField(db_comment="전화번호는 '010-xxxx-xxxx' 형식으로만 받음", error_messages={'invalid': "전화번호는 '010-xxxx-xxxx' 형식으로만 받습니다", 'unique': '이미 존재하는 전화번호입니다'}, max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^010-\\d{4}-\\d{4}$')])),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_comment='가입일')),
                ('is_active', models.BooleanField(db_comment='로그인 가능 여부', default=True)),
                ('major', models.CharField(db_comment='학부/학과명. 개발의 편의를 위해 CharField로 받고, 형식은 자유. 단, 비어있으면 안됨', max_length=32)),
                ('grade', models.IntegerField(default=1, error_messages={'invalid': '학년은 1~4만 가능합니다'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('position', models.IntegerField(choices=[(0, '신입'), (1, '투수'), (2, '포수'), (3, '1루수'), (4, '2루수'), (5, '3루수'), (6, '유격수'), (7, '좌익수'), (8, '중견수'), (9, '우익수')], default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
                'db_table_comment': '야구부 부원들의 정보를 담는 테이블',
            },
        ),
    ]
